# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playingaround.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(542, 369)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(120, 120, 241, 51))
        self.b1.setStyleSheet("background-color : Lavender")
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 542, 24))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuaktuellerMonat = QtWidgets.QMenu(self.menubar)
        self.menuaktuellerMonat.setObjectName("menuaktuellerMonat")
        self.menuMonatsabrechnungen = QtWidgets.QMenu(self.menubar)
        self.menuMonatsabrechnungen.setObjectName("menuMonatsabrechnungen")
        self.menuStatistiken = QtWidgets.QMenu(self.menubar)
        self.menuStatistiken.setObjectName("menuStatistiken")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStatistiken = QtWidgets.QAction(MainWindow)
        self.actionStatistiken.setObjectName("actionStatistiken")
        self.menuMonatsabrechnungen.addSeparator()
        self.menubar.addAction(self.menuaktuellerMonat.menuAction())
        self.menubar.addAction(self.menuMonatsabrechnungen.menuAction())
        self.menubar.addAction(self.menuStatistiken.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b1.setText(_translate("MainWindow", " Monatsabrechnung erstellen"))
        self.menuaktuellerMonat.setTitle(_translate("MainWindow", "Aktueller Monat"))
        self.menuMonatsabrechnungen.setTitle(_translate("MainWindow", "Monatsabrechnungen"))
        self.menuStatistiken.setTitle(_translate("MainWindow", "Statistiken"))
        self.actionStatistiken.setText(_translate("MainWindow", "Statistiken"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
